config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'recipes#public'
  get '/public_recipes', to: 'recipes#public', as: :public_recipes
  get '/shoppingList_list/:recipe_id', to: 'recipe_foods#shopping_list', as: :shoppingList_list
  patch '/recipes/:id', to: 'recipes#mark_as_public', as: :update_recipe
  resources :users
  resources :foods, except: [:update]

  resources :recipes do
    resources :recipe_foods, only: [:create, :new, :edit, :update, :destroy]
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    can :read, :all
    can :manage, :all, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods
  validates :name, :price, :measurement_unit, presence: true
  accepts_nested_attributes_for :recipe_foods
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  has_many :foods, through: :recipe_foods
  validates :name, :description, :cooking_time, :prep_time, presence: true

  after_initialize :init
  def init
    self.recipe_foods_count ||= 0
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe, counter_cache: true
  belongs_to :food

  validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes, dependent: :destroy
  has_many :foods, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email password password_confirmation name])
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[email password])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!

  def index
    @foods = current_user.foods
  end

  def show
    redirect_to foods_path
  end

  def create
    @food = current_user.foods.new(food_params)
    if @food.save
      redirect_to foods_path
    else
      render :new
    end
  end

  def new
    @food = Food.new
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    flash[:notice] = 'Food deleted successfully'
    redirect_to request.path
  end

  private

  def food_params
    params.require(:food).permit(:name, :price, :measurement_unit)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!
  def edit
    @recipe_food = RecipeFood.find(params[:id])
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.update(recipe_food_params)
      flash[:succes] = 'Recipe food updated successfully'
      redirect_to recipe_path(@recipe_food.recipe)
    else
      flash[:succes] = 'Recipe food update failed'
      render :edit
    end
  end

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new(recipe_food_params)
    if @recipe_food.save
      redirect_to @recipe
    else
      render :new
    end
  end

  def shopping_list
    # select user's recipe
    foods = Food.includes(:recipes).where(user: current_user)
    # filter food missing for all recipes
    @missing_food = foods.filter { |food| food.recipes.blank? }
    # calculate sum
    @total_price = @missing_food.sum(&:price)
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: [:public]

  def index
    @recipes = current_user.recipes.includes(:recipe_foods, :user)
  end

  def show
    @recipe = Recipe.includes(:recipe_foods).find(params[:id])
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = 'Recipe deleted successfully'
    redirect_to recipes_path
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to @recipe
    else
      render :new
    end
  end

  def new
    @recipe = Recipe.new
  end

  def public
    @recipes = Recipe.includes(:recipe_foods, :foods,
                               :user).where(public: true).order(created_at: :desc).map do |recipe|
      {
        id: recipe.id,
        name: recipe.name,
        description: recipe.description,
        author: recipe.user.name,
        created_at: recipe.created_at,
        items: recipe.recipe_foods_count,
        total_price: recipe.foods.map(&:price).sum
      }
    end
  end

  def mark_as_public
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)
    redirect_to @recipe
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :prep_time, :cooking_time)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show
    redirect_to foods_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_form.html.erb
<%= form_with model: @food, local: true do |form|%>
        <%= form.text_field :name, placeholder:"Food name", class:"form_control" %>
        <%= form.text_field :measurement_unit,placeholder:"measurement unit", class:"form_control" %>
        <%= form.number_field :price, value: number_to_currency(form.object.price.to_f), step: :any , placeholder:"Food price", class:"form_control"%>
    <%= form.submit "Create", class: "btn btn-info btn-sm" %>
<% end %>

app/views/foods/index.html.erb
<h3 class="text-center mt-4">My Foods </h3>
<table class="table table-ligth table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Food name</th>
      <th scope="col">Measurement unit</th>
      <th scope="col">Price</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each_with_index do |food, index| %>
    <tr>
      <th scope="row"><%=index%></th>
      <td><%= food.name %></td>
      <td><%= food.measurement_unit %></td>
      <td>$<%= food.price %></td>
      <td><%= button_to 'delete', food, data: { confirm: "This action will delete the item "}, method: :delete , class:"btn btn-sm btn-danger" if can? :manage, food%></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Add food", new_food_path, class: "btn btn-info btn-sm ml-3 mt-3"%>

app/views/foods/new.html.erb
<h1>Add new food</h1>
<%= render 'form'%>

app/views/foods/show.html.erb
<h1>Foods#show</h1>
<p>Find me in app/views/foods/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%# <script src="https://cdn.tailwindcss.com"></script> %>
  </head>

  <body>
    <%= render 'layouts/shared/log_menu' %>
    <div class="flash">
      <% flash.each do |name, message| %>
            <div class="alert alert-<%=name%>" role="alert">
                  <%= message %>
            </div>
      <% end %>
    </div>
    <div class="container mt-3">
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/shared/_log_menu.html.erb
<header class="p-3 bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-around">
            <h3><a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                Recipe App
            </a></h3>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><%= link_to "Public recipes", public_recipes_path, class:"nav-link px-2 text-while"%></li>
                <% if user_signed_in? %>     
                    <li><%= link_to "Foods", foods_path, class:"nav-link px-2 text-while"%></li>
                    <li><%= link_to link_to "Recipes", recipes_path, class:"nav-link px-2 text-while"%></li>
                <% end %>
            </ul>
            <% if user_signed_in? %>
                <div class="text-end">
                    <%= button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: false }, class:"btn btn-warning" %>
                </div>  
            <% else %>
                <div class="text-end">
                    <%= link_to 'Sign up', new_user_registration_path, class:"btn btn-salmon" %>
                    <%= link_to 'Login', new_user_session_path, class: "btn btn-outline-light me-2"%>
                </div>
            <% end %>
        </div>
    </div>
  </header>

app/views/recipe_foods/_form.html.erb
<%= form_with model: [@recipe, @recipe.recipe_foods.build], local: true do |f| %>
    <div class="field">
        <%= f.label :Ingredient, class:"form-label" %><br>
        <%= f.select :food_id, current_user.foods.collect {|food| [food.name, food.id]},{ include_blank: true} , class:"custom-select", id:"inputGroupSelect01" %><br>
    </div>

    <div class="field">
        <%= f.label :quantity, class:"form-label" %><br>
        <%= f.number_field :quantity ,  class:"form-control" , required: true, placeholder: '1',  min: 1%><br>
    </div>

    <div class="fiel">
        <%= f.submit "Add ingredient", class:"btn btn-success form-control" %>
    </div>
<% end %>

app/views/recipe_foods/edit.html.erb
<h4 class="text-center mt-3">Edit ingredient </h4>
<div class="d-flex justify-content-center mt-4" style="width: 60%; margin:auto">
    <%= form_with  model: @recipe_food, url: { action: "update"}, local: true, class:"input-form"  do |f|%>
        <div class="form-group">
            <%= f.select :food_id, current_user.foods.collect {|food| [food.name, food.id]},{ include_blank: true} , class:"custom-select form-control", id:"inputGroupSelect01" %><br>
        </div>

        <div class="form-group">
            <%= f.number_field :quantity ,  class:"form-control" , required: true, placeholder: 'quantity',  min: 1%><br>
        </div>
        <%=link_to "back", recipe_path(@recipe_food.recipe.id)%>  <%= f.submit "Update", class:"btn btn-sm btn-warning " %>
    <% end %>
    <br /> 
</div>
<div class="text-center">
 
</div>

app/views/recipe_foods/new.html.erb
<h1>new ingredients to <%= @recipe.name %>  </h1>
<%= render 'form'%>

app/views/recipe_foods/shoppingList.html.erb
<h3 class="text-center mt-4"> Shopping list </h3>
<p class="text-info h5">Amount of foods to buy: <%= @missing_food.count %></p>
<p class="text-info h6">Total value of of food needed: $ <%= @total_price %></p>

<table class="table table-ligth table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Quantity</th> 
      <th scope="col">Unit Price</th>
    </tr>
  </thead>
  <tbody>
  <% @missing_food.each_with_index do |food, index|%>
    <tr>
      <th scope="row"><%=index%></th>
      <td><%=food.name%></td>
      <td><%= food.measurement_unit %></td>
      <td>$<%=food.price%></td>
    </tr>
    <%end%>
  </tbody>
</table>
<p><= <%=link_to :back%></p>

app/views/recipe_foods/shopping_list.html.erb
<h3 class="text-center mt-4"> Shopping list </h3>
<p class="text-info h5">Amount of foods to buy: <%= @missing_food.count %></p>
<p class="text-info h6">Total value of of food needed: $ <%= @total_price %></p>

<table class="table table-ligth table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Quantity</th> 
      <th scope="col">Unit Price</th>
    </tr>
  </thead>
  <tbody>
  <% @missing_food.each_with_index do |food, index|%>
    <tr>
      <th scope="row"><%=index%></th>
      <td><%=food.name%></td>
      <td><%= food.measurement_unit %></td>
      <td>$<%=food.price%></td>
    </tr>
    <%end%>
  </tbody>
</table>
<p><= <%=link_to :back%></p>

app/views/recipes/_form.html.erb
<%= form_with model: @recipe, local: true do |form|%>
  <%= form.text_field :name, placeholder:"Recipe name", class:"form_control" %>
  <%= form.number_field :prep_time, step: :any , placeholder:"Prep time", class:"form_control"%>
  <%= form.number_field :cooking_time, step: :any , placeholder:"Cooking time", class:"form_control"%>
  <%= form.text_field :description, placeholder:"Description", class:"form_control" %>
  <%= form.submit "Create", class: "btn btn-info btn-sm" %>
<% end %>

app/views/recipes/_index.html.erb
<div class="list-group w-80">
    <% recipes.each do |recipe| %>
        <div class="list-group-item list-group-item-action rounded-3 d-flex gap-4 py-3 px-3" aria-current="true">
            <div class="d-flex gap-4 w-100 justify-content-between">
                <div>
                    <h4 class="mb-0"><%=link_to recipe[:name], recipe_path(recipe[:id]) %></h4>
                    <small class="opacity-50 text-nowrap">by <%= recipe[:author]  %></small>
                    <p class="mb-0 opacity-75"><%= recipe[:description].truncate(100)%></p>
                    <p class="text-info"><%= recipe[:items] %> items ~ total price: $<%= recipe[:total_price] %> </p>
                </div>
                <small class="opacity-50 text-nowrap"><%= time_ago_in_words(recipe[:created_at]) %></small>
            </div>
        </div>
    <% end%>
</div>

app/views/recipes/index.html.erb
<h4 class="text-center">My Recipes</h4>
<div class="list-group w-80">
    <% @recipes.each do |recipe| %>
        <div class="list-group-item list-group-item-action rounded-3 d-flex gap-4 py-3 px-3" aria-current="true">
            <div class="d-flex gap-4 w-100 justify-content-between">
                <div>
                    <h4 class="mb-0"><%=link_to recipe.name, recipe %></h4>
                    <p class="mb-0 opacity-75"><%= recipe.description.truncate(100)%></p>
                    <p class="text-info"><%= recipe.recipe_foods_count %> ingredients</p>
                    <% if can? :manage, recipe %>
                        <%= button_to 'delete', recipe, data: { confirm: "This action will delete the item "}, method: :delete, class:"btn btn-sm btn-danger"%>
                    <% end %>
                </div>
                <small class="opacity-50 text-nowrap"><%= time_ago_in_words(recipe.created_at) %></small>
            </div>
        </div>
    <% end%>
</div>

<%= link_to "Add recipe", new_recipe_path, class: "btn btn-info btn-sm ml-3 my-3"%>

app/views/recipes/new.html.erb
<h1>Add new recipe</h1>
<%= render 'form'%>

app/views/recipes/public.html.erb
<%= render partial: 'index', locals: {recipes: @recipes} %>

app/views/recipes/show.html.erb
<div class="card d-flex justify-content-center mt-4" style="width: 80%; margin:auto">
  <div class="card-body">
    <div class="d-flex justify-content-between">
      <h5 class="card-title"><%= @recipe.name%></h5>
      <% if can? :manage, @recipe%>
        <% if @recipe.public %>
          <%= button_to "Mark as private", update_recipe_path(@recipe), method: :patch, class:"btn btn-sm btn-light" %>
        <% else %>
          <%= button_to "Mark as public", update_recipe_path(@recipe), method: :patch, class:"btn btn-sm btn-light"  %>
        <% end %>
      <% end %>
    </div>
    <h6 class="card-subtitle mb-2 text-info">Preparation time: <%= @recipe.prep_time%>(min)</h6>
    <h6 class="card-subtitle mb-2 text-info">cooking time: <%= @recipe.cooking_time%>(min)</h6>
    <small class="opacity-50 text-nowrap"> Description</small>
    <p class="card-text"><%= @recipe.description%></p>
    
       <!-- Button trigger modal -->
        <div class="d-flex justify-content-between">
        <% if can? :manage, @recipe %>
          <button type="button" class="btn btn-sm btn-info" data-toggle="modal" data-target="#exampleModalCenter">add ingredient</button>
        <% end %>
          <%= link_to "Generate shopping list", shoppingList_list_path(@recipe), class: "btn btn-sm btn-light btn-shop" %>
        </div>
    
  </div>
</div>
<h4 class="mt-4 text-center">Ingredients </h4>
<div class="card d-flex justify-content-center mt-4" style="width: 80%; margin:auto">
    <table class="table table-ligth table-hover">
        <% if @recipe.foods.empty? %>
            <p>No food in this recipe</p>
        <% else %>
            <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Food name</th>
                <th scope="col">Food Price</th>
                <th scope="col">quantity</th>
                <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                <% @recipe.recipe_foods.each_with_index do |ingredient, index|%>
                <tr>
                    <th scope="row"><%=index%></th>
                    <td><%= ingredient.food.name %></td>
                    <td><%= ingredient.quantity %></td>
                    <td>$ <%= ingredient.food.price %></td>
                    
                    <% if can? :manage, @recipe %>
                    <td>
                        <%= link_to "Edit", edit_recipe_recipe_food_path(@recipe, ingredient), class:"btn btn-sm btn-primary" if can? :manage, @recipe%>
                    </td> 
                    <td>
                        <%= link_to "Delete", recipe_recipe_food_path(@recipe, ingredient), method: :delete, class:"btn btn-sm btn-danger" if can? :manage, @recipe %>
                    </td>
                    <% end %>
                </tr>
                <% end %>
            </tbody>
        <% end %>
    </table>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Add ingredients for <%=@recipe.name%></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "recipe_foods/form"%>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>